//
// Coord.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Coord: Codable {

    public var lat: String?
    public var lon: String?

    public init(lat: String?, lon: String?) {
        self.lat = lat
        self.lon = lon
    }


}

