//
// ListingData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ListingData: Codable {

    public var listingId: String?
    public var deviceId: String?
    public var price: String?
    public var address: String?
    public var numBeds: String?
    public var numBaths: String?
    public var leaseTerms: String?
    public var leaseType: String?
    public var descriptionText: String?
    public var dateAdded: String?
    public var petPolicy: String?
    public var smokingPolicy: String?
    public var parkingPolicy: String?
    public var laundryData: String?

    public init(listingId: String?, deviceId: String?, price: String?, address: String?, numBeds: String?, numBaths: String?, leaseTerms: String?, leaseType: String?, descriptionText: String?, dateAdded: String?, petPolicy: String?, smokingPolicy: String?, parkingPolicy: String?, laundryData: String?) {
        self.listingId = listingId
        self.deviceId = deviceId
        self.price = price
        self.address = address
        self.numBeds = numBeds
        self.numBaths = numBaths
        self.leaseTerms = leaseTerms
        self.leaseType = leaseType
        self.descriptionText = descriptionText
        self.dateAdded = dateAdded
        self.petPolicy = petPolicy
        self.smokingPolicy = smokingPolicy
        self.parkingPolicy = parkingPolicy
        self.laundryData = laundryData
    }


}

