//
// RenterMatch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RenterMatch: Codable {

    public var listingId: String?
    public var renterId: String?
    public var dateMatched: String?
    public var active: String?
    public var matched: String?
    public var locationCode: String?
    public var photoId: String?

    public init(listingId: String?, renterId: String?, dateMatched: String?, active: String?, matched: String?, locationCode: String?, photoId: String?) {
        self.listingId = listingId
        self.renterId = renterId
        self.dateMatched = dateMatched
        self.active = active
        self.matched = matched
        self.locationCode = locationCode
        self.photoId = photoId
    }


}

