//
// Weather.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Weather: Codable {

    public var coord: Coord?
    public var weather: [WeatherWeather]?

    public init(coord: Coord?, weather: [WeatherWeather]?) {
        self.coord = coord
        self.weather = weather
    }


}

