//
// WeatherWeather.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WeatherWeather: Codable {

    public var main: String?

    public init(main: String?) {
        self.main = main
    }


}

