//
// Weather.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Weather: Codable {

    public var coords: Any?

    public init(coords: Any?) {
        self.coords = coords
    }


}

