//
// UserData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserData: Codable {

    public var deviceId: String?
    public var userType: String?
    public var name: String?
    public var company: String?
    public var birthday: String?
    public var occupation: String?
    public var education: String?
    public var priceRange: String?
    public var listings: String?
    public var maritalStatus: String?
    public var smoker: String?
    public var drinker: String?
    public var dependents: String?
    public var felon: String?
    public var photoId: String?
    public var city: String?

    public init(deviceId: String?, userType: String?, name: String?, company: String?, birthday: String?, occupation: String?, education: String?, priceRange: String?, listings: String?, maritalStatus: String?, smoker: String?, drinker: String?, dependents: String?, felon: String?, photoId: String?, city: String?) {
        self.deviceId = deviceId
        self.userType = userType
        self.name = name
        self.company = company
        self.birthday = birthday
        self.occupation = occupation
        self.education = education
        self.priceRange = priceRange
        self.listings = listings
        self.maritalStatus = maritalStatus
        self.smoker = smoker
        self.drinker = drinker
        self.dependents = dependents
        self.felon = felon
        self.photoId = photoId
        self.city = city
    }


}

